### ISSUE TITLE
translate into compliant format

### ISSUE THREAD

**Issue by fdschneider** [EcologicalTraitData/ETS#1]
The csv file now contains the original information on the traitdata standard. For integration in GFBio we need to provide [SKOS](https://www.w3.org/TR/2009/REC-skos-reference-20090818/) or [OWL](https://www.w3.org/TR/owl-features/) format. Also, the [OBO](http://www.obofoundry.org/principles/fp-002-format.html) could be a more human readable way of storing the primary source, which then may be transferred into the other formats by an R script.

**Comment by fdschneider** [comment]
I discussed with David Fichtmüller today and we made the following distinction: 

- our csv file is the 'source file' of the glossary, defining the terms and setting the URIs.
- the auto-generated html file (adding documentation and explanations) is an appropriate human-readable form of the glossary 
- a machine readable version can be generated and hosted by GFBio in RDF format.
- the Github repository and issue tracker, and maybe its Wiki can be used for discussion and revision on individual terms.  

That said, there is no need to migrate the csv into any other format.  However, there could be an option to use the [GFBio Biowiki](https://terminology-sandbox.biowikifarm.net/wiki/Browse_Ontology_Vocabularies#Concepts) for the discussion and definition, which would directly produce a RDF ontology.

**Comment by nadjasimons** [comment]
I am not really sure how we would use the GFBio Biowiki. Would we use their URIs as a reference for our terms and add additional terms to the Wiki?
On first sight, I find the terms in the Biowiki very confusing. I am not sure what the actual benefits would be and if those are worth the time needed to update our current terms.

**Comment by fdschneider** [comment]
Yes, thats the thing.  The wiki is rather unintuitive and requires some training. Technically, migration would be simple. Our terms would be added to the Wiki by GFBio. They would automatically receive a stable URI which would be deployed in RDF format and rendered into a unintuitive web-view (just as for other ontologies hosted on the Terminology Service). 

I think its better to keep the development on Github and work on the CSV file, while having revisions discussed in the Github Issues. The reference website would be our own Github page. I tried to formalize this in the new README.md. 
  
Nonetheless GFBio would provide stable URIs (#3), which we would use in our CSV file as Identifier, and which are forwarded to the terms in our html document.

**Comment by DavidFichtmueller** [comment]
OWL version of the standard is now in this repo, along with the steps to generate it.
