### ISSUE TITLE
Versioning scheme for terms and entire standard

### ISSUE THREAD

**Issue by caterinap** [EcologicalTraitData/ETS#10]
**Changes on both git page and csv**
- There is no version number in many definitions, should it be v0.1 by default?
- `date issued` is missing for several terms (e.g. `MeasurementOrFact`, `taxonID`) - check if this is ok
- Some of the `date issued` or `date modified` are in different formats (month/day or day/month)
- In `Traitlist` : all `valueTypes` are missing
- `scientificName` - `Definition` : "Original character string provided as species name by the data owner (kept for reference and continueity)" [typo in continuity]
- `occurrenceID `-  `Definition` : a bona fide global unique identifier [maybe not clear what "bona fide" means?]
- `warnings`, `relationSource`, `eventID`: put capital letters at the beginning of sentences (for harmonisation)
- `datasetID` and `statisticalMethod` - `Comment` : "e.g." could be "Examples" (for harmonisation)
- `taxonRank`, `kingdom`, `phylum`, `class`, `order`, `family`, `genus`: some have a `date issued` and some have a `date modified` but the date is the same. Should they be all `date issued`?
- `author` - `Comment` : Examples: [remove or fill the field]
- some fields have semicolons in their description, this caused me quite some problems when reading the csv: replace them?
- in `valueType`; only "Date" have a capital letter
- `year`, `month`, `day` - `Description`: description is not harmonised: e.g. "The four-digit year, at which" vs "The ordinal month, in which" vs "The integer day of the month on which"

**Mismatches: in git but not csv or _vice versa_**
- in csv some `description` fields have a space before the beginning of the text (in `locationID`, `eventDate`, `statisticalMethod`, `Exploratory`)
- Maybe not a problem but csv is not in the same order as git : csv is ordered Traitdata, Taxon, MeasurementOrFact; git is ordered Traitdata, Metadata, Traitlist..

**Comment by fdschneider** [comment]
I did 
- remove the term-level versioning from the source file. 
- add a 'FirstIssuedIn' field, which points to the version of the standard where this term has been added. The 'Deprecated' and 'Replaces'/'ReplacedBy' fields are sufficient for versioning. 
- add a statement on versioning in the 'about' and 'contributing' page
