### ISSUE TITLE
Errors in dates for DateIssued and DateModified

### ISSUE THREAD

**Issue by DavidFichtmueller** [EcologicalTraitData/ETS#11]
Most dates in the document are formatted according to the American notation of month/day/year. There are however three cases, that use the format day/month/year, causing ambiguity and wrong dates. 

Two terms use the DateIssued of "5/9/2017" with is supposed to be the fifth of September. Both terms have the version "v0.4". The other terms from version 4 have issue dates from 8/24/2017 till 10/24/2017. Version 3 terms were all created on 7/7/2017. 

Two terms have the DateModified of "1/11/2017" which is supposed to be the first of November, as the terms were all created on 7/7/2017. 

Seven terms have the DateModified of "15/11/2017" which is an obvious error, no ambiguity here. 

To avoid such errors in the future, I would suggest to switch to the ISO 8601 format of YY-MM-DD ([related XKCD](https://xkcd.com/1179/)).

**Comment by fdschneider** [comment]
Yes, that's a mess. Which of these dates do we need for a referencing of terms, anyway? See #10. I tend to eliminate a version number for the terms, this is not adding any information. The dates are similarly impracticable. More important are the releases of the entire vocabulary and the "deprecated" and "replacedBy"/"replaces" fields for labelling out-dated fields and cross-reference them to the newer terms.
