### ISSUE TITLE
Several typos in the definitions/comments 

### ISSUE THREAD

**Issue by DavidFichtmueller** [EcologicalTraitData/ETS#12]
in v0.7 I noticed several spelling issues in the definitions or comments of the term. I wasn't sure whether to modify the .csv file and make a pull request or list them here. 

One general question is whether the text is written in American English (AE) or British English (BE). So far it is a mixture of both, but it should be consistent.
 
Words that are currently written in BE are:
* in definition of measurementValue: "Standardised" instead of "Standardized"
* in definition of author: "organisation" instead of "organization"
* in comment of measurementMethod: "standardised" instead of "standardized" 
* in comment of eventDate: "analysing" instead of "analyzing"
* in comment of valueType: "behaviour" instead of "behavior"  
* in comment of valueType: "specialisation" instead of "specialization"

Words that are currently written in AE are:
* in definition of decimalLongitude: "center" instead of "centre"
* in definition of decimalLatitude: "center" instead of "centre"
* in comment of valueType: "color" instead of "colour"

One of these two blocks should be corrected.

General spelling errors:
* in definition of scientificName: "continueity" instead of "continuity"
* in definition of references: "preferrably" instead of "preferably" 
* in definition of preparations: "occurence" instead of "occurrence" 
* in comment of verbatimLocality: "darwin core" instead of "DarwinCore" 
* in comment of BEPlotID: "exploratories" instead of "Exploratories" 
* in comment of relationSource: "precice" instead of "precise"
* several cases of double spaces, they should be removed with Search & Replace

**Comment by fdschneider** [comment]
I
