### ISSUE TITLE
harmonize URI scheme

### ISSUE THREAD

**Issue by fdschneider** [EcologicalTraitData/ETS#20]
URIs often do not match the case of the Term. Infact spelling is fairly inconsistent. The URI root is `http://terminologies.gfbio.org/terms/ETS/` and complemented by a string identical to the Term itself (with mixed case spelling) as in `valueType`, or modified to a lowercase string as in the case of  `traitvaluestd`. This irrgularity can cause wrong calls of the API or broken reference to the human readable website. 
The URI resolves to the human readable website only if it is correctly mapped to the lower case URL of style `https://terminologies.gfbio.org/terms/ets/pages/#term`.

**Comment by DavidFichtmueller** [comment]
The issue with resolving the URIs is different from the inconsistent spelling. The resolving issue now forwards all URIs to the HTML representation with a lower case html-anchor, as can be seen here:  http://terminologies.gfbio.org/terms/ETS/measurementMethod 
The other issues about the inconsistent capitalization of the URIs has been addressed in the linked commit (f61f4cce4478ca704858ffdd7ee0523f04e864aa).
