### ISSUE TITLE
define URI scheme

### ISSUE THREAD

**Issue by fdschneider** [EcologicalTraitData/ETS#5]
We should define the URI Scheme of the terms. 

First of all, see #3. 
Second, we have several options for setting our own URI addresses. 

1. The current solution is provided by the Github Pages URL, extended by the hashtagged ID, which works as a direct link to a first-level header. The Github URL is pretty long and might put off users seeming not institutional. 
2. We could forward the entire page to a different domain, e.g. this could be based on https://www.bexis.uni-jena.de/ or on an own domain. If we run our own domain, this would provide short URIs, and also brand our project better.  But this also requires some maintenance and money (for a domain name hosting service). If maintenance stopps and no one pays for the domain in the future, the URIs will break.  
3. The URIs could be forwarded to our Github site through GFBios Terminology server. That has the advantage that the URIs could free of a hashtag and could be moved to a different place in the future. The server could also relay the request to the website if it comes from a web-browser, or to the RDF if it comes from a software.  It would have a base URL like this: http://terminologies.gfbio.org/terms/ETS/

In my opinion the latter is the most sustainable solution. It seemed to me that it would be solved in the same process as importing the RDF ontology, and GFBio would be very open to do this. 

Any opinions here? Otherwise I would push forward option 3.

**Comment by nadjasimons** [comment]
I agree with you that option 3 sounds best.

**Comment by caterinap** [comment]
yep, same, the third would be the better and if it doesn't work, the first is also OK.

**Comment by fdschneider** [comment]
I had an exchange with David Fichtmüller and he confirmed that they can provide static URIs to our terms *and* they can host the entire website on gfbio.org.  

David is now taking care of the URI forwarding. 

We were also discussing Versioning on URIs. I think it is most important, that URIs of our terms remain static, if they are referred to by a static data publication (e.g. on Figshare). Thus you always know according to which version the dataset was constructed.  

A newer dataset would refer to the then newest version of the data standard. In this new version, terms that have been updated get a versioned URI (http://terminologies.gfbio.org/terms/ETS/v2/scientificname), while identical terms remain with their original URI.  

One open question is, whether the website is hosted on GFBio or on Github. Github is very fast and flexible and can be updated very easily using git. However, the URL of GFBio would give the whole publication more consistency. Since the website is static and is not updated frequently, this might be ideal.

**Comment by DavidFichtmueller** [comment]
URI scheme has been adjusted with 1a5134f0f7ac5400431e9dc0973e3040fbb255b9 . All URLs are now resolvable by the GFBio TS in human and machine readable versions.
